name: labhouse_radio
description: "This is a technical test for LabHouse. It is an application where you can listen to different radios and add them to your favourites."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

isar_version: &isar_version 3.1.0+1

dependency_overrides:
  #Issue with isar and riverpod_lint: https://github.com/isar/isar/issues/1505
  analyzer: 6.3.0
  meta: 1.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.6
  audio_session: 0.1.18
  audio_service: 0.18.12
  just_audio: 0.9.36
  http: 1.2.0
  flutter_riverpod: 2.4.10
  riverpod_annotation: 2.3.4
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  isar: *isar_version

  isar_flutter_libs: *isar_version
  path_provider: 2.1.2
  marquee: 2.2.3
  cached_network_image: 3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.4.8
  very_good_analysis: 5.1.0
  custom_lint: 0.6.0
  riverpod_lint: 2.3.9
  riverpod_generator: 2.3.11
  freezed: 2.4.7
  json_serializable: 6.7.1
  isar_generator: *isar_version
  flutter_native_splash: 2.3.10

flutter:
  uses-material-design: true

flutter_native_splash:
  image: assets/splash.png
  color: "#6f43c0"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
